spring:
    cloud:
        gateway:
            routes:
                - id: subscription-service
                  uri: lb://subscription-service
                  predicates:
                      - Path=/servcad/**
                - id: subscription-payment-service
                  uri: lb://subscription-service
                  predicates:
                      - Path=/registrarpagamento/**
    application:
        name: subscription-gateway
server:
    port: 8080
eureka:
    client:
        fetch-registry: true
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8001/eureka/}